footprint: [[0.50,0.50],[-0.50,0.50],[-0.50,-0.50],[0.50,-0.50]]
inflation_radius: 1.5
cost_scaling_factor: 15.0

observation_sources: laser_1

laser_1: {sensor_frame: laser_1_link , data_type: LaserScan, topic: laser_1/scan_filtered, marking: true, clearing: true, obstacle_range: 5, raytrace_range: 5}



